[functions]
  directory = "packages/nouns-webapp/functions"

[build]
  command = "git submodule update --init --recursive --depth=1 && yarn workspace @nouns/webapp build"
  publish = "packages/nouns-webapp/build"
