name: Contracts CD

on:
  release:
    types:
      - created

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn build

      - name: Run contract tests
        run: |
          cd packages/nouns-contracts
          yarn test

      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
